name = "tlg-bot"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[vars]
# Telegram Bot Token (mock for now, replace in production)
BOT_TOKEN = "8818123904:AAG2pNcsMrcROzjAUcXgQQsw6xY7d0oXQ6w"
ADMIN_CHAT_ID = "6147744511"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce-bot-db"
database_id = "832453d2-a833-4c88-b9ac-f83bcabe1dd0" # Replace with real ID when deploying to Cloudflare
