ALTER TABLE profiles ADD COLUMN national_code TEXT;
ALTER TABLE profiles ADD COLUMN date_of_birth TEXT;
ALTER TABLE profiles ADD COLUMN wallet_status TEXT DEFAULT 'UNVERIFIED';
ALTER TABLE profiles ADD COLUMN wallet_balance INTEGER DEFAULT 0;

ALTER TABLE invoices ADD COLUMN type TEXT DEFAULT 'PRODUCT_PURCHASE';
